#!/bin/bash
set -euo pipefail
ROOT="$(pwd)/work/implementation/intel"
PREFIX="$ROOT/prefix"
cmake -S "$ROOT/x265/x265_4.3/source" -B "$ROOT/x265-10-build" -G Ninja -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=26.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$PREFIX" -DENABLE_ASSEMBLY=OFF -DENABLE_CLI=OFF -DENABLE_SHARED=OFF -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5
cmake --build "$ROOT/x265-10-build" -j 2
cp "$ROOT/x265-10-build/libx265.a" "$ROOT/x265-build/libx265_main10.a"
cmake -S "$ROOT/x265/x265_4.3/source" -B "$ROOT/x265-build" -G Ninja -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=26.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$PREFIX" -DENABLE_ASSEMBLY=OFF -DENABLE_CLI=OFF -DENABLE_SHARED=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DLINKED_10BIT=ON -DEXTRA_LIB=x265_main10.a -DEXTRA_LINK_FLAGS="-L$ROOT/x265-build"
cmake --build "$ROOT/x265-build" -j 2
cmake --install "$ROOT/x265-build"
